# Generated by Django 3.1.7 on 2021-04-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csvdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('open', models.CharField(max_length=255)),
                ('high', models.CharField(max_length=255)),
                ('low', models.CharField(max_length=255)),
                ('close', models.CharField(max_length=255)),
                ('adj_close', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
            ],
        ),
    ]
